### ISSUE TITLE
Observatorio de redes sociales sobre comentarios sobre contaminación o palabras relacionadas con los efectos de la contaminación.

### ISSUE THREAD

**Issue by PhoenixAlx** [oslugr/contaminAND#9]
Mi idea es hacer una nube de palabras con un corpus creado a partir de tweets que mencionen la palabra contaminación en la última semana estando geolocalizados en granada...más adelante verremos si se puede analizar algo más que la nube de palabras. Ell paquete NLTK de python es magia

**Comment by JJ** [comment]
Genial.
